#!/bin/bash
# Create a dated text file at a specific location and append text to it.
#
# Usage:
#   $ notes something you want to jot down (appends that text to the file)
#   $ xclip -o | notes                     (appends your clipboard to the file)
#   $ notes                                (opens the file in your editor)
#
# Produces:
#   YYYY-MM.txt in your $NOTES_DIRECTORY (this is set below).

set -e

readonly NOTES_DIRECTORY=${NOTES_DIRECTORY}/$(date +%Y_%m_%d)
readonly NOTES_EDITOR="${EDITOR}"

readonly NOTES_FILE="general.md"
readonly NOTES_PATH="${NOTES_DIRECTORY}/${NOTES_FILE}"

if [ ! -d "${NOTES_DIRECTORY}" ]; then
    while true; do
        read -rp "${NOTES_DIRECTORY} does not exist, do you want to create it? (y/n) " yn
        case "${yn}" in
            [Yy]* ) mkdir -p "${NOTES_DIRECTORY}"; break;;
            [Nn]* ) exit;;
            * ) echo "Please answer y or n";;
        esac
    done
fi

if [ ! -f $NOTES_PATH ]; then
    touch $NOTES_PATH
    chmod 755 $NOTES_PATH
fi

if [ ${#} -eq 0 ]; then
    if [ -p "/dev/stdin" ]; then
        (cat; printf "\n\n") >> "${NOTES_PATH}"
    else
	echo $NOTES_EDITOR
        eval "${NOTES_EDITOR}" "${NOTES_PATH}"
    fi
else
    printf "%s\n\n" "${*}" >> "${NOTES_PATH}"
fi
